/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels.payments;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Pololoers
 */
public class PaymentBillingPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentBillingPanel
     */
    public PaymentBillingPanel() {
        initComponents();

        initializePaymentTable();
        initializeBillingBreakdownTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchKeyword = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblStudentIdValue = new javax.swing.JLabel();
        lblStudentNameValue = new javax.swing.JLabel();
        lblGradeLevelValue = new javax.swing.JLabel();
        lblEnrollmentIdValue = new javax.swing.JLabel();
        lblEnrollmentStatusValue = new javax.swing.JLabel();
        lblTotalFeeValue = new javax.swing.JLabel();
        lblTotalPaidValue = new javax.swing.JLabel();
        lblBalanceValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayments = new javax.swing.JTable();
        btnRecordPayment = new javax.swing.JButton();
        btnGenerateSOA = new javax.swing.JButton();
        cmbPaymentPlan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBillingBreakdown = new javax.swing.JTable();
        cmbSchoolYearFilter = new javax.swing.JComboBox<>();
        btnFilterByYear = new javax.swing.JButton();
        lblYearBalance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtSearchKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchKeywordActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");

        btnRefresh.setText("Refresh");

        lblStudentIdValue.setText("Student ID");

        lblStudentNameValue.setText("Student Name");

        lblGradeLevelValue.setText("Grade Level");

        lblEnrollmentIdValue.setText("Enrollment ID");

        lblEnrollmentStatusValue.setText("Enrollment Status");

        lblTotalFeeValue.setText("Total Fee");

        lblTotalPaidValue.setText("Total Paid");

        lblBalanceValue.setText("Balance");

        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPayments);

        btnRecordPayment.setText("Record Payment");

        btnGenerateSOA.setText("Generate SOA");

        cmbPaymentPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUARTERLY", "SEMI_ANNUAL", "ANNUAL" }));

        tblBillingBreakdown.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBillingBreakdown);

        cmbSchoolYearFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFilterByYear.setText("Filter by Year");

        lblYearBalance.setText("Year Balance");

        jLabel1.setText("Student ID");

        jLabel2.setText("Student Name");

        jLabel3.setText("Grade Level");

        jLabel4.setText("Enrollment ID");

        jLabel5.setText("Enrollment Status");

        jLabel6.setText("Total Fee");

        jLabel7.setText("Total Paid");

        jLabel8.setText("Balance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPaymentPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRecordPayment)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGenerateSOA))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSearchKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearch)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRefresh))
                                    .addComponent(cmbSchoolYearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFilterByYear))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEnrollmentStatusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEnrollmentIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalFeeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalPaidValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBalanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGradeLevelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStudentNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStudentIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(246, 246, 246)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblYearBalance))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentIdValue)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentNameValue)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeLevelValue)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnrollmentIdValue)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnrollmentStatusValue)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalFeeValue)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPaidValue)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBalanceValue)
                            .addComponent(jLabel8))
                        .addGap(11, 11, 11)
                        .addComponent(cmbPaymentPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRecordPayment)
                            .addComponent(btnGenerateSOA))
                        .addGap(30, 30, 30)
                        .addComponent(cmbSchoolYearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFilterByYear))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYearBalance)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchKeywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeywordActionPerformed

    public String getSearchKeyword() {
        return txtSearchKeyword.getText().trim();
    }

    public JTextField getTxtSearchKeyword() {
        return txtSearchKeyword;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public JTable getTblPayments() {
        return tblPayments;
    }

    public JButton getBtnRecordPayment() {
        return btnRecordPayment;
    }

    public JButton getBtnGenerateSOA() {
        return btnGenerateSOA;
    }

    public JLabel getLblStudentIdValue() {
        return lblStudentIdValue;
    }

    public JLabel getLblStudentNameValue() {
        return lblStudentNameValue;
    }

    public JLabel getLblGradeLevelValue() {
        return lblGradeLevelValue;
    }

    public JLabel getLblEnrollmentIdValue() {
        return lblEnrollmentIdValue;
    }

    public JLabel getLblEnrollmentStatusValue() {
        return lblEnrollmentStatusValue;
    }

    public JLabel getLblTotalFeeValue() {
        return lblTotalFeeValue;
    }

    public JLabel getLblTotalPaidValue() {
        return lblTotalPaidValue;
    }

    public JLabel getLblBalanceValue() {
        return lblBalanceValue;
    }

    public String getSelectedPaymentPlan() {
        Object selected = cmbPaymentPlan.getSelectedItem();

        return selected == null
                ? ""
                : selected.toString();
    }

    public JComboBox<String> getCmbPaymentPlan() {
        return cmbPaymentPlan;
    }

    public void initializePaymentTable() {

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Payment ID",
                            "Date",
                            "Amount",
                            "Method",
                            "Plan",
                            "Reference No."
                        }
                ) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblPayments.setModel(model);

        tblPayments.getTableHeader().setReorderingAllowed(false);

        tblPayments.setRowHeight(25);
    }

    public JTable getTblBillingBreakdown() {
        return tblBillingBreakdown;
    }

    public void initializeBillingBreakdownTable() {

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Description",
                            "Amount"
                        }
                ) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblBillingBreakdown.setModel(model);
        tblBillingBreakdown.getTableHeader().setReorderingAllowed(false);
        tblBillingBreakdown.setRowHeight(25);
    }

    public JComboBox<String> getCmbSchoolYearFilter() {
        return cmbSchoolYearFilter;
    }

    public JButton getBtnFilterByYear() {
        return btnFilterByYear;
    }

    public JLabel getLblYearBalance() {
        return lblYearBalance;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilterByYear;
    private javax.swing.JButton btnGenerateSOA;
    private javax.swing.JButton btnRecordPayment;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbPaymentPlan;
    private javax.swing.JComboBox<String> cmbSchoolYearFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBalanceValue;
    private javax.swing.JLabel lblEnrollmentIdValue;
    private javax.swing.JLabel lblEnrollmentStatusValue;
    private javax.swing.JLabel lblGradeLevelValue;
    private javax.swing.JLabel lblStudentIdValue;
    private javax.swing.JLabel lblStudentNameValue;
    private javax.swing.JLabel lblTotalFeeValue;
    private javax.swing.JLabel lblTotalPaidValue;
    private javax.swing.JLabel lblYearBalance;
    private javax.swing.JTable tblBillingBreakdown;
    private javax.swing.JTable tblPayments;
    private javax.swing.JTextField txtSearchKeyword;
    // End of variables declaration//GEN-END:variables
}
