/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.dialogs.students;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Pololoers
 */
public class StudentEnrollmentDetailsDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentEnrollmentDetailsDialog.class.getName());

    /**
     * Creates new form StudentEnrollmentDetailsDialog
     */
    public StudentEnrollmentDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentInformationTitle = new javax.swing.JLabel();
        lblStudentIdValue = new javax.swing.JLabel();
        lblGradeLevelValue = new javax.swing.JLabel();
        lblStudentNameValue = new javax.swing.JLabel();
        lblAgeValue = new javax.swing.JLabel();
        lblBirthdateValue = new javax.swing.JLabel();
        lblAddressValue = new javax.swing.JLabel();
        lblPreviousSchoolValue = new javax.swing.JLabel();
        lblHasAllergiesValue = new javax.swing.JLabel();
        lblMedicalDetailsValue = new javax.swing.JLabel();
        lblGuardianInformationTitle = new javax.swing.JLabel();
        lblGuardianNameValue = new javax.swing.JLabel();
        lblGuardianContactValue = new javax.swing.JLabel();
        lblGuardianAddressValue = new javax.swing.JLabel();
        lblGuardianOccupationValue = new javax.swing.JLabel();
        lblRelationshipValue = new javax.swing.JLabel();
        lblEnrollmentInformationTitle = new javax.swing.JLabel();
        lblEnrollmentIdValue = new javax.swing.JLabel();
        lblDiagnosticScheduleValue = new javax.swing.JLabel();
        lblDiagnosticStatusValue = new javax.swing.JLabel();
        lblPsaStatusValue = new javax.swing.JLabel();
        lblSf10Value = new javax.swing.JLabel();
        lblGoodMoralStatusValue = new javax.swing.JLabel();
        lblEnrollmentStatusValue = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Enrollment Details");
        setModal(true);
        setResizable(false);

        lblStudentInformationTitle.setText("Student Information");
        lblStudentInformationTitle.setMaximumSize(new java.awt.Dimension(114, 16));
        lblStudentInformationTitle.setMinimumSize(new java.awt.Dimension(114, 16));

        lblStudentIdValue.setText("Student ID");
        lblStudentIdValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblStudentIdValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblGradeLevelValue.setText("Grade Level");
        lblGradeLevelValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblGradeLevelValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblStudentNameValue.setText("Student Name");
        lblStudentNameValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblStudentNameValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblAgeValue.setText("Age");
        lblAgeValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblAgeValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblBirthdateValue.setText("Birthdate");
        lblBirthdateValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblBirthdateValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblAddressValue.setText("Address");
        lblAddressValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblAddressValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblPreviousSchoolValue.setText("Previous School");
        lblPreviousSchoolValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblPreviousSchoolValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblHasAllergiesValue.setText("Allergies");
        lblHasAllergiesValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblHasAllergiesValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblMedicalDetailsValue.setText("Medical Details");
        lblMedicalDetailsValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblMedicalDetailsValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblGuardianInformationTitle.setText("Guardian Information");
        lblGuardianInformationTitle.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianNameValue.setText("Name");
        lblGuardianNameValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianContactValue.setText("Contact");
        lblGuardianContactValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianAddressValue.setText("Address");
        lblGuardianAddressValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianOccupationValue.setText("Occupation");
        lblGuardianOccupationValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblRelationshipValue.setText("Relationship");
        lblRelationshipValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblEnrollmentInformationTitle.setText("Enrollment Information");
        lblEnrollmentInformationTitle.setPreferredSize(new java.awt.Dimension(124, 16));

        lblEnrollmentIdValue.setText("Enrollment ID");

        lblDiagnosticScheduleValue.setText("Diagnostic Schedule");

        lblDiagnosticStatusValue.setText("Diagnostic Status");

        lblPsaStatusValue.setText("PSA Submission Status");

        lblSf10Value.setText("SF10 Submission Status");

        lblGoodMoralStatusValue.setText("Good Moral Submission Status");

        lblEnrollmentStatusValue.setText("Enrollment Status");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPreviousSchoolValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddressValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBirthdateValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAgeValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStudentNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGradeLevelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStudentIdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHasAllergiesValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStudentInformationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMedicalDetailsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblGuardianNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGuardianContactValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGuardianAddressValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGuardianOccupationValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGuardianInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRelationshipValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnrollmentInformationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(301, 301, 301))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPsaStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiagnosticStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiagnosticScheduleValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnrollmentIdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnrollmentStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGoodMoralStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSf10Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnClose)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnrollmentInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnrollmentIdValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDiagnosticScheduleValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDiagnosticStatusValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPsaStatusValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSf10Value)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGoodMoralStatusValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnrollmentStatusValue))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGuardianInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGuardianNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGradeLevelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGuardianContactValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGuardianAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGuardianOccupationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBirthdateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRelationshipValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreviousSchoolValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHasAllergiesValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMedicalDetailsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addComponent(btnClose)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                StudentEnrollmentDetailsDialog dialog = new StudentEnrollmentDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JLabel getLblStudentIdValue() {
        return lblStudentIdValue;
    }

    public JLabel getLblGradeLevelValue() {
        return lblGradeLevelValue;
    }

    public JLabel getLblStudentNameValue() {
        return lblStudentNameValue;
    }

    public JLabel getLblAgeValue() {
        return lblAgeValue;
    }

    public JLabel getLblBirthdateValue() {
        return lblBirthdateValue;
    }

    public JLabel getLblAddressValue() {
        return lblAddressValue;
    }

    public JLabel getLblPreviousSchoolValue() {
        return lblPreviousSchoolValue;
    }

    public JLabel getLblHasAllergiesValue() {
        return lblHasAllergiesValue;
    }

    public JLabel getLblMedicalDetailsValue() {
        return lblMedicalDetailsValue;
    }

    public JLabel getLblGuardianNameValue() {
        return lblGuardianNameValue;
    }

    public JLabel getLblGuardianContactValue() {
        return lblGuardianContactValue;
    }

    public JLabel getLblGuardianAddressValue() {
        return lblGuardianAddressValue;
    }

    public JLabel getLblGuardianOccupationValue() {
        return lblGuardianOccupationValue;
    }

    public JLabel getLblRelationshipValue() {
        return lblRelationshipValue;
    }

    public JLabel getLblEnrollmentIdValue() {
        return lblEnrollmentIdValue;
    }

    public JLabel getLblDiagnosticScheduleValue() {
        return lblDiagnosticScheduleValue;
    }

    public JLabel getLblDiagnosticStatusValue() {
        return lblDiagnosticStatusValue;
    }

    public JLabel getLblPsaStatusValue() {
        return lblPsaStatusValue;
    }

    public JLabel getLblSf10StatusValue() {
        return lblSf10Value;
    }

    public JLabel getLblGoodMoralStatusValue() {
        return lblGoodMoralStatusValue;
    }

    public JLabel getLblEnrollmentStatusValue() {
        return lblEnrollmentStatusValue;
    }

    public JButton getBtnClose() {
        return btnClose;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAddressValue;
    private javax.swing.JLabel lblAgeValue;
    private javax.swing.JLabel lblBirthdateValue;
    private javax.swing.JLabel lblDiagnosticScheduleValue;
    private javax.swing.JLabel lblDiagnosticStatusValue;
    private javax.swing.JLabel lblEnrollmentIdValue;
    private javax.swing.JLabel lblEnrollmentInformationTitle;
    private javax.swing.JLabel lblEnrollmentStatusValue;
    private javax.swing.JLabel lblGoodMoralStatusValue;
    private javax.swing.JLabel lblGradeLevelValue;
    private javax.swing.JLabel lblGuardianAddressValue;
    private javax.swing.JLabel lblGuardianContactValue;
    private javax.swing.JLabel lblGuardianInformationTitle;
    private javax.swing.JLabel lblGuardianNameValue;
    private javax.swing.JLabel lblGuardianOccupationValue;
    private javax.swing.JLabel lblHasAllergiesValue;
    private javax.swing.JLabel lblMedicalDetailsValue;
    private javax.swing.JLabel lblPreviousSchoolValue;
    private javax.swing.JLabel lblPsaStatusValue;
    private javax.swing.JLabel lblRelationshipValue;
    private javax.swing.JLabel lblSf10Value;
    private javax.swing.JLabel lblStudentIdValue;
    private javax.swing.JLabel lblStudentInformationTitle;
    private javax.swing.JLabel lblStudentNameValue;
    // End of variables declaration//GEN-END:variables
}
