/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.dialogs.students;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Pololoers
 */
public class StudentEnrollmentDetailsDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentEnrollmentDetailsDialog.class.getName());

    /**
     * Creates new form StudentEnrollmentDetailsDialog
     */
    public StudentEnrollmentDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentInformationTitle = new javax.swing.JLabel();
        lblStudentIdValue = new javax.swing.JLabel();
        lblGradeLevelValue = new javax.swing.JLabel();
        lblStudentNameValue = new javax.swing.JLabel();
        lblAgeValue = new javax.swing.JLabel();
        lblBirthdateValue = new javax.swing.JLabel();
        lblAddressValue = new javax.swing.JLabel();
        lblPreviousSchoolValue = new javax.swing.JLabel();
        lblHasAllergiesValue = new javax.swing.JLabel();
        lblMedicalDetailsValue = new javax.swing.JLabel();
        lblGuardianInformationTitle = new javax.swing.JLabel();
        lblGuardianNameValue = new javax.swing.JLabel();
        lblGuardianContactValue = new javax.swing.JLabel();
        lblGuardianAddressValue = new javax.swing.JLabel();
        lblGuardianOccupationValue = new javax.swing.JLabel();
        lblRelationshipValue = new javax.swing.JLabel();
        lblEnrollmentInformationTitle = new javax.swing.JLabel();
        lblEnrollmentIdValue = new javax.swing.JLabel();
        lblDiagnosticScheduleValue = new javax.swing.JLabel();
        lblDiagnosticStatusValue = new javax.swing.JLabel();
        lblPsaStatusValue = new javax.swing.JLabel();
        lblSf10Value = new javax.swing.JLabel();
        lblGoodMoralStatusValue = new javax.swing.JLabel();
        lblEnrollmentStatusValue = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Enrollment Details");
        setModal(true);
        setResizable(false);

        lblStudentInformationTitle.setText("Student Information");
        lblStudentInformationTitle.setMaximumSize(new java.awt.Dimension(114, 16));
        lblStudentInformationTitle.setMinimumSize(new java.awt.Dimension(114, 16));

        lblStudentIdValue.setText("Student ID");
        lblStudentIdValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblStudentIdValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblGradeLevelValue.setText("Grade Level");
        lblGradeLevelValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblGradeLevelValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblStudentNameValue.setText("Student Name");
        lblStudentNameValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblStudentNameValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblAgeValue.setText("Age");
        lblAgeValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblAgeValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblBirthdateValue.setText("Birthdate");
        lblBirthdateValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblBirthdateValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblAddressValue.setText("Address");
        lblAddressValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblAddressValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblPreviousSchoolValue.setText("Previous School");
        lblPreviousSchoolValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblPreviousSchoolValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblHasAllergiesValue.setText("Allergies");
        lblHasAllergiesValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblHasAllergiesValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblMedicalDetailsValue.setText("Medical Details");
        lblMedicalDetailsValue.setMaximumSize(new java.awt.Dimension(114, 16));
        lblMedicalDetailsValue.setMinimumSize(new java.awt.Dimension(114, 16));

        lblGuardianInformationTitle.setText("Guardian Information");
        lblGuardianInformationTitle.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianNameValue.setText("Name");
        lblGuardianNameValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianContactValue.setText("Contact");
        lblGuardianContactValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianAddressValue.setText("Address");
        lblGuardianAddressValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblGuardianOccupationValue.setText("Occupation");
        lblGuardianOccupationValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblRelationshipValue.setText("Relationship");
        lblRelationshipValue.setPreferredSize(new java.awt.Dimension(120, 16));

        lblEnrollmentInformationTitle.setText("Enrollment Information");

        lblEnrollmentIdValue.setText("Enrollment ID");

        lblDiagnosticScheduleValue.setText("Diagnostic Schedule");

        lblDiagnosticStatusValue.setText("Diagnostic Status");

        lblPsaStatusValue.setText("PSA Submission Status");

        lblSf10Value.setText("SF10 Submission Status");

        lblGoodMoralStatusValue.setText("Good Moral Submission Status");

        lblEnrollmentStatusValue.setText("Enrollment Status");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("Enrollment ID");

        jLabel2.setText("Diagnostic Schedule");

        jLabel3.setText("Diagnostic Status");

        jLabel4.setText("PSA Submission Status");

        jLabel5.setText("SF10 Submission Status");

        jLabel6.setText("Good Moral Submission Status");

        jLabel7.setText("Enrollment Satus");

        jLabel8.setText("Name");

        jLabel9.setText("Contact");

        jLabel10.setText("Address");

        jLabel11.setText("Occupation");

        jLabel12.setText("Relationship");

        jLabel13.setText("Student ID");

        jLabel14.setText("Grade Level");

        jLabel15.setText("Student Name");

        jLabel16.setText("Age");

        jLabel17.setText("Birthdate");

        jLabel18.setText("Address");

        jLabel19.setText("Previous School");

        jLabel20.setText("Allergies");

        jLabel21.setText("Medical Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPreviousSchoolValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddressValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthdateValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgeValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGradeLevelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentIdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHasAllergiesValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedicalDetailsValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(318, 318, 318))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGuardianInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRelationshipValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblGuardianNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblGuardianContactValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblGuardianAddressValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblGuardianOccupationValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnClose))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnrollmentInformationTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSf10Value)
                            .addComponent(lblGoodMoralStatusValue)
                            .addComponent(lblPsaStatusValue)
                            .addComponent(lblDiagnosticStatusValue)
                            .addComponent(lblDiagnosticScheduleValue)
                            .addComponent(lblEnrollmentIdValue)
                            .addComponent(lblEnrollmentStatusValue))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuardianInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnrollmentInformationTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuardianNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnrollmentIdValue)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeLevelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuardianContactValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagnosticScheduleValue)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuardianAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagnosticStatusValue)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuardianOccupationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPsaStatusValue)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBirthdateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelationshipValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSf10Value)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGoodMoralStatusValue)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreviousSchoolValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnrollmentStatusValue)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHasAllergiesValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalDetailsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                StudentEnrollmentDetailsDialog dialog = new StudentEnrollmentDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JLabel getLblStudentIdValue() {
        return lblStudentIdValue;
    }

    public JLabel getLblGradeLevelValue() {
        return lblGradeLevelValue;
    }

    public JLabel getLblStudentNameValue() {
        return lblStudentNameValue;
    }

    public JLabel getLblAgeValue() {
        return lblAgeValue;
    }

    public JLabel getLblBirthdateValue() {
        return lblBirthdateValue;
    }

    public JLabel getLblAddressValue() {
        return lblAddressValue;
    }

    public JLabel getLblPreviousSchoolValue() {
        return lblPreviousSchoolValue;
    }

    public JLabel getLblHasAllergiesValue() {
        return lblHasAllergiesValue;
    }

    public JLabel getLblMedicalDetailsValue() {
        return lblMedicalDetailsValue;
    }

    public JLabel getLblGuardianNameValue() {
        return lblGuardianNameValue;
    }

    public JLabel getLblGuardianContactValue() {
        return lblGuardianContactValue;
    }

    public JLabel getLblGuardianAddressValue() {
        return lblGuardianAddressValue;
    }

    public JLabel getLblGuardianOccupationValue() {
        return lblGuardianOccupationValue;
    }

    public JLabel getLblRelationshipValue() {
        return lblRelationshipValue;
    }

    public JLabel getLblEnrollmentIdValue() {
        return lblEnrollmentIdValue;
    }

    public JLabel getLblDiagnosticScheduleValue() {
        return lblDiagnosticScheduleValue;
    }

    public JLabel getLblDiagnosticStatusValue() {
        return lblDiagnosticStatusValue;
    }

    public JLabel getLblPsaStatusValue() {
        return lblPsaStatusValue;
    }

    public JLabel getLblSf10StatusValue() {
        return lblSf10Value;
    }

    public JLabel getLblGoodMoralStatusValue() {
        return lblGoodMoralStatusValue;
    }

    public JLabel getLblEnrollmentStatusValue() {
        return lblEnrollmentStatusValue;
    }

    public JButton getBtnClose() {
        return btnClose;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAddressValue;
    private javax.swing.JLabel lblAgeValue;
    private javax.swing.JLabel lblBirthdateValue;
    private javax.swing.JLabel lblDiagnosticScheduleValue;
    private javax.swing.JLabel lblDiagnosticStatusValue;
    private javax.swing.JLabel lblEnrollmentIdValue;
    private javax.swing.JLabel lblEnrollmentInformationTitle;
    private javax.swing.JLabel lblEnrollmentStatusValue;
    private javax.swing.JLabel lblGoodMoralStatusValue;
    private javax.swing.JLabel lblGradeLevelValue;
    private javax.swing.JLabel lblGuardianAddressValue;
    private javax.swing.JLabel lblGuardianContactValue;
    private javax.swing.JLabel lblGuardianInformationTitle;
    private javax.swing.JLabel lblGuardianNameValue;
    private javax.swing.JLabel lblGuardianOccupationValue;
    private javax.swing.JLabel lblHasAllergiesValue;
    private javax.swing.JLabel lblMedicalDetailsValue;
    private javax.swing.JLabel lblPreviousSchoolValue;
    private javax.swing.JLabel lblPsaStatusValue;
    private javax.swing.JLabel lblRelationshipValue;
    private javax.swing.JLabel lblSf10Value;
    private javax.swing.JLabel lblStudentIdValue;
    private javax.swing.JLabel lblStudentInformationTitle;
    private javax.swing.JLabel lblStudentNameValue;
    // End of variables declaration//GEN-END:variables
}
