/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels.enrollment;

import javax.swing.JButton;

/**
 *
 * @author Pololoers
 */
public class EnrollmentMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentMenuPanel
     */
    public EnrollmentMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewStudentEnrollment = new javax.swing.JButton();
        btnOldStudentEnrollment = new javax.swing.JButton();
        btnEditStudentInformation = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnNewStudentEnrollment.setText("New Student Enrollment");

        btnOldStudentEnrollment.setText("Old Student Enrollment");

        btnEditStudentInformation.setText("Edit Student Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOldStudentEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewStudentEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(394, 394, 394))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnNewStudentEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOldStudentEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public JButton getBtnNewStudentEnrollment() {
        return btnNewStudentEnrollment;
    }

    public JButton getBtnOldStudentEnrollment() {
        return btnOldStudentEnrollment;
    }

    public JButton getBtnEditStudentInformation() {
        return btnEditStudentInformation;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditStudentInformation;
    private javax.swing.JButton btnNewStudentEnrollment;
    private javax.swing.JButton btnOldStudentEnrollment;
    // End of variables declaration//GEN-END:variables
}
