/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels.enrollment;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Pololoers
 */
public class NewStudentEnrollmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewStudentEnrollmentPanel
     */
    public NewStudentEnrollmentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbGradeLevel = new javax.swing.JComboBox<>();
        txtStudentFirstName = new javax.swing.JTextField();
        txtStudentMiddleName = new javax.swing.JTextField();
        txtStudentLastName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStudentAddress = new javax.swing.JTextArea();
        spnAge = new javax.swing.JSpinner();
        dateBirthdate = new com.toedter.calendar.JDateChooser();
        txtPreviousSchool = new javax.swing.JTextField();
        chkHasAllergies = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMedicalDetails = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtGuardianFirstName = new javax.swing.JTextField();
        txtGuardianLastName = new javax.swing.JTextField();
        txtGuardianContactNumber = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGuardianAddress = new javax.swing.JTextArea();
        txtGuardianOccupation = new javax.swing.JTextField();
        cmbRelationship = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dateDiagnosticSchedule = new com.toedter.calendar.JDateChooser();
        chkDiagnosticPassed = new javax.swing.JCheckBox();
        chkPsaSubmitted = new javax.swing.JCheckBox();
        chkSf10Submitted = new javax.swing.JCheckBox();
        chkGoodMoralSubmitted = new javax.swing.JCheckBox();
        cmbEnrollmentStatus = new javax.swing.JComboBox<>();
        btnSaveEnrollment = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Student Information");

        cmbGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nursery", "Junior Kindergarten", "Senior Kindergarten", "1", "2", "3", "4", "5", "6" }));

        txtStudentFirstName.setText("First Name");
        txtStudentFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentFirstNameActionPerformed(evt);
            }
        });

        txtStudentMiddleName.setText("Middle Name");

        txtStudentLastName.setText("Last Name");

        txtStudentAddress.setColumns(20);
        txtStudentAddress.setRows(5);
        jScrollPane1.setViewportView(txtStudentAddress);

        txtPreviousSchool.setText("Previous School");

        chkHasAllergies.setText("Has allergies?");

        txtMedicalDetails.setColumns(20);
        txtMedicalDetails.setRows(5);
        jScrollPane2.setViewportView(txtMedicalDetails);

        jLabel2.setText("Guardian Information");

        txtGuardianFirstName.setText("First Name");
        txtGuardianFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianFirstNameActionPerformed(evt);
            }
        });

        txtGuardianLastName.setText("LastName");
        txtGuardianLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianLastNameActionPerformed(evt);
            }
        });

        txtGuardianContactNumber.setText("Contact Number");
        txtGuardianContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianContactNumberActionPerformed(evt);
            }
        });

        txtGuardianAddress.setColumns(20);
        txtGuardianAddress.setRows(5);
        jScrollPane3.setViewportView(txtGuardianAddress);

        txtGuardianOccupation.setText("Occupation");

        cmbRelationship.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father", "Mother", "Guardian", "Grandparent", "Sibling", "Relative" }));

        jLabel3.setText("Enrollment Information");

        chkDiagnosticPassed.setText("Passed Diagnostic");
        chkDiagnosticPassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDiagnosticPassedActionPerformed(evt);
            }
        });

        chkPsaSubmitted.setText("PSA Submitted");
        chkPsaSubmitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPsaSubmittedActionPerformed(evt);
            }
        });

        chkSf10Submitted.setText("SF10 Submitted");
        chkSf10Submitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSf10SubmittedActionPerformed(evt);
            }
        });

        chkGoodMoralSubmitted.setText("Good Moral Submitted");
        chkGoodMoralSubmitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGoodMoralSubmittedActionPerformed(evt);
            }
        });

        cmbEnrollmentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Enrolled", "Rejected" }));

        btnSaveEnrollment.setText("Save");

        btnClear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveEnrollment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtStudentMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkHasAllergies, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(spnAge)
                                    .addComponent(dateBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPreviousSchool)
                                    .addComponent(txtStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGuardianFirstName)
                            .addComponent(txtGuardianLastName)
                            .addComponent(txtGuardianContactNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addComponent(txtGuardianOccupation)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRelationship, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(dateDiagnosticSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkDiagnosticPassed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkPsaSubmitted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkSf10Submitted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkGoodMoralSubmitted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEnrollmentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(326, 326, 326))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGuardianFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateDiagnosticSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuardianLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDiagnosticPassed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuardianContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPsaSubmitted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkSf10Submitted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkGoodMoralSubmitted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEnrollmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGuardianOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPreviousSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHasAllergies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEnrollment)
                    .addComponent(btnClear))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    STUDENT INFORMATION
    public JComboBox<String> getCmbGradeLevel() {
        return cmbGradeLevel;
    }

    public JTextField getTxtStudentFirstName() {
        return txtStudentFirstName;
    }

    public JTextField getTxtStudentMiddleName() {
        return txtStudentMiddleName;
    }

    public JTextField getTxtStudentLastName() {
        return txtStudentLastName;
    }

    public JTextArea getTxtStudentAddress() {
        return txtStudentAddress;
    }

    public JSpinner getSpnAge() {
        return spnAge;
    }

    public JDateChooser getDateBirthdate() {
        return dateBirthdate;
    }

    public JTextField getTxtPreviousSchool() {
        return txtPreviousSchool;
    }

    public JCheckBox getChkHasAllergies() {
        return chkHasAllergies;
    }

    public JTextArea getTxtMedicalDetails() {
        return txtMedicalDetails;
    }

//    GUARDIAN INFORMATION
    public JTextField getTxtGuardianFirstName() {
        return txtGuardianFirstName;
    }

    public JTextField getTxtGuardianLastName() {
        return txtGuardianLastName;
    }

    public JTextField getTxtGuardianContactNumber() {
        return txtGuardianContactNumber;
    }

    public JTextArea getTxtGuardianAddress() {
        return txtGuardianAddress;
    }

    public JTextField getTxtGuardianOccupation() {
        return txtGuardianOccupation;
    }

    public JComboBox<String> getCmbRelationship() {
        return cmbRelationship;
    }

//    ENROLLMENT
    public JDateChooser getDateDiagnosticSchedule() {
        return dateDiagnosticSchedule;
    }

    public JCheckBox getChkDiagnosticPassed() {
        return chkDiagnosticPassed;
    }

    public JCheckBox getChkPsaSubmitted() {
        return chkPsaSubmitted;
    }

    public JCheckBox getChkSf10Submitted() {
        return chkSf10Submitted;
    }

    public JCheckBox getChkGoodMoralSubmitted() {
        return chkGoodMoralSubmitted;
    }

    public JComboBox<String> getCmbEnrollmentStatus() {
        return cmbEnrollmentStatus;
    }

//    BUTTONS
    public JButton getBtnSaveEnrollment() {
        return btnSaveEnrollment;
    }

    public JButton getBtnClear() {
        return btnClear;
    }

    private void txtStudentFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentFirstNameActionPerformed

    private void txtGuardianFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianFirstNameActionPerformed

    private void txtGuardianLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianLastNameActionPerformed

    private void txtGuardianContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianContactNumberActionPerformed

    private void chkDiagnosticPassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDiagnosticPassedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDiagnosticPassedActionPerformed

    private void chkPsaSubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPsaSubmittedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPsaSubmittedActionPerformed

    private void chkSf10SubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSf10SubmittedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSf10SubmittedActionPerformed

    private void chkGoodMoralSubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGoodMoralSubmittedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkGoodMoralSubmittedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSaveEnrollment;
    private javax.swing.JCheckBox chkDiagnosticPassed;
    private javax.swing.JCheckBox chkGoodMoralSubmitted;
    private javax.swing.JCheckBox chkHasAllergies;
    private javax.swing.JCheckBox chkPsaSubmitted;
    private javax.swing.JCheckBox chkSf10Submitted;
    private javax.swing.JComboBox<String> cmbEnrollmentStatus;
    private javax.swing.JComboBox<String> cmbGradeLevel;
    private javax.swing.JComboBox<String> cmbRelationship;
    private com.toedter.calendar.JDateChooser dateBirthdate;
    private com.toedter.calendar.JDateChooser dateDiagnosticSchedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextArea txtGuardianAddress;
    private javax.swing.JTextField txtGuardianContactNumber;
    private javax.swing.JTextField txtGuardianFirstName;
    private javax.swing.JTextField txtGuardianLastName;
    private javax.swing.JTextField txtGuardianOccupation;
    private javax.swing.JTextArea txtMedicalDetails;
    private javax.swing.JTextField txtPreviousSchool;
    private javax.swing.JTextArea txtStudentAddress;
    private javax.swing.JTextField txtStudentFirstName;
    private javax.swing.JTextField txtStudentLastName;
    private javax.swing.JTextField txtStudentMiddleName;
    // End of variables declaration//GEN-END:variables
}
