/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels.enrollment;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Pololoers
 */
public class NewStudentEnrollmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewStudentEnrollmentPanel
     */
    public NewStudentEnrollmentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbGradeLevel = new javax.swing.JComboBox<>();
        txtStudentFirstName = new javax.swing.JTextField();
        txtStudentMiddleName = new javax.swing.JTextField();
        txtStudentLastName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStudentAddress = new javax.swing.JTextArea();
        spnAge = new javax.swing.JSpinner();
        dateBirthdate = new com.toedter.calendar.JDateChooser();
        txtPreviousSchool = new javax.swing.JTextField();
        chkHasAllergies = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMedicalDetails = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtGuardianFirstName = new javax.swing.JTextField();
        txtGuardianLastName = new javax.swing.JTextField();
        txtGuardianContactNumber = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGuardianAddress = new javax.swing.JTextArea();
        txtGuardianOccupation = new javax.swing.JTextField();
        cmbRelationship = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dateDiagnosticSchedule = new com.toedter.calendar.JDateChooser();
        chkDiagnosticPassed = new javax.swing.JCheckBox();
        chkPsaSubmitted = new javax.swing.JCheckBox();
        chkSf10Submitted = new javax.swing.JCheckBox();
        chkGoodMoralSubmitted = new javax.swing.JCheckBox();
        cmbEnrollmentStatus = new javax.swing.JComboBox<>();
        btnSaveEnrollment = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Student Information");

        cmbGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nursery", "Junior Kindergarten", "Senior Kindergarten", "1", "2", "3", "4", "5", "6" }));
        cmbGradeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGradeLevelActionPerformed(evt);
            }
        });

        txtStudentFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentFirstNameActionPerformed(evt);
            }
        });

        txtStudentAddress.setColumns(20);
        txtStudentAddress.setRows(5);
        jScrollPane1.setViewportView(txtStudentAddress);

        chkHasAllergies.setText("Has allergies?");

        txtMedicalDetails.setColumns(20);
        txtMedicalDetails.setRows(5);
        jScrollPane2.setViewportView(txtMedicalDetails);

        jLabel2.setText("Guardian Information");

        txtGuardianFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianFirstNameActionPerformed(evt);
            }
        });

        txtGuardianLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianLastNameActionPerformed(evt);
            }
        });

        txtGuardianContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianContactNumberActionPerformed(evt);
            }
        });

        txtGuardianAddress.setColumns(20);
        txtGuardianAddress.setRows(5);
        jScrollPane3.setViewportView(txtGuardianAddress);

        txtGuardianOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianOccupationActionPerformed(evt);
            }
        });

        cmbRelationship.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father", "Mother", "Guardian", "Grandparent", "Sibling", "Relative" }));

        jLabel3.setText("Enrollment Information");

        chkDiagnosticPassed.setText("Passed Diagnostic");
        chkDiagnosticPassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDiagnosticPassedActionPerformed(evt);
            }
        });

        chkPsaSubmitted.setText("PSA Submitted");
        chkPsaSubmitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPsaSubmittedActionPerformed(evt);
            }
        });

        chkSf10Submitted.setText("SF10 Submitted");
        chkSf10Submitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSf10SubmittedActionPerformed(evt);
            }
        });

        chkGoodMoralSubmitted.setText("Good Moral Submitted");
        chkGoodMoralSubmitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGoodMoralSubmittedActionPerformed(evt);
            }
        });

        cmbEnrollmentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Enrolled", "Rejected" }));

        btnSaveEnrollment.setText("Save");

        btnClear.setText("Clear");

        jLabel4.setText("Grade Level");

        jLabel5.setText("First Name");

        jLabel6.setText("Middle Name");

        jLabel7.setText("Last Name");

        jLabel8.setText("Address");

        jLabel9.setText("Age");

        jLabel10.setText("Birthdate");

        jLabel11.setText("Previous School");

        jLabel12.setText("Medical Details");

        jLabel13.setText("First Name");

        jLabel14.setText("Last Name");

        jLabel15.setText("Contact Number");

        jLabel16.setText("Address");

        jLabel17.setText("Occupation");

        jLabel18.setText("Relationship");

        jLabel19.setText("Diagnostic Schedule");

        jLabel20.setText("Enrollment Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(txtStudentMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(cmbGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dateBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtGuardianFirstName)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtGuardianLastName)
                                                .addComponent(txtGuardianContactNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane3)
                                                .addComponent(txtGuardianOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16))
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkDiagnosticPassed)
                                            .addComponent(chkPsaSubmitted)
                                            .addComponent(chkSf10Submitted)
                                            .addComponent(chkGoodMoralSubmitted)
                                            .addComponent(jLabel19)
                                            .addComponent(dateDiagnosticSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20)
                                            .addComponent(cmbEnrollmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))))
                            .addComponent(jLabel12)
                            .addComponent(txtPreviousSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(chkHasAllergies)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(btnSaveEnrollment)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(dateBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreviousSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkHasAllergies))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGuardianFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(8, 8, 8)
                                .addComponent(txtGuardianLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGuardianContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateDiagnosticSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDiagnosticPassed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkPsaSubmitted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkSf10Submitted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkGoodMoralSubmitted)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEnrollmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGuardianOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(cmbRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEnrollment)
                    .addComponent(btnClear))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

//    STUDENT INFORMATION
    public JComboBox<String> getCmbGradeLevel() {
        return cmbGradeLevel;
    }

    public JTextField getTxtStudentFirstName() {
        return txtStudentFirstName;
    }

    public JTextField getTxtStudentMiddleName() {
        return txtStudentMiddleName;
    }

    public JTextField getTxtStudentLastName() {
        return txtStudentLastName;
    }

    public JTextArea getTxtStudentAddress() {
        return txtStudentAddress;
    }

    public JSpinner getSpnAge() {
        return spnAge;
    }

    public JDateChooser getDateBirthdate() {
        return dateBirthdate;
    }

    public JTextField getTxtPreviousSchool() {
        return txtPreviousSchool;
    }

    public JCheckBox getChkHasAllergies() {
        return chkHasAllergies;
    }

    public JTextArea getTxtMedicalDetails() {
        return txtMedicalDetails;
    }

//    GUARDIAN INFORMATION
    public JTextField getTxtGuardianFirstName() {
        return txtGuardianFirstName;
    }

    public JTextField getTxtGuardianLastName() {
        return txtGuardianLastName;
    }

    public JTextField getTxtGuardianContactNumber() {
        return txtGuardianContactNumber;
    }

    public JTextArea getTxtGuardianAddress() {
        return txtGuardianAddress;
    }

    public JTextField getTxtGuardianOccupation() {
        return txtGuardianOccupation;
    }

    public JComboBox<String> getCmbRelationship() {
        return cmbRelationship;
    }

//    ENROLLMENT
    public JDateChooser getDateDiagnosticSchedule() {
        return dateDiagnosticSchedule;
    }

    public JCheckBox getChkDiagnosticPassed() {
        return chkDiagnosticPassed;
    }

    public JCheckBox getChkPsaSubmitted() {
        return chkPsaSubmitted;
    }

    public JCheckBox getChkSf10Submitted() {
        return chkSf10Submitted;
    }

    public JCheckBox getChkGoodMoralSubmitted() {
        return chkGoodMoralSubmitted;
    }

    public JComboBox<String> getCmbEnrollmentStatus() {
        return cmbEnrollmentStatus;
    }

//    BUTTONS
    public JButton getBtnSaveEnrollment() {
        return btnSaveEnrollment;
    }

    public JButton getBtnClear() {
        return btnClear;
    }

    private void txtStudentFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentFirstNameActionPerformed

    private void txtGuardianFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianFirstNameActionPerformed

    private void txtGuardianLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianLastNameActionPerformed

    private void txtGuardianContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianContactNumberActionPerformed

    private void chkDiagnosticPassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDiagnosticPassedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDiagnosticPassedActionPerformed

    private void chkPsaSubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPsaSubmittedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPsaSubmittedActionPerformed

    private void chkSf10SubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSf10SubmittedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSf10SubmittedActionPerformed

    private void chkGoodMoralSubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGoodMoralSubmittedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkGoodMoralSubmittedActionPerformed

    private void cmbGradeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGradeLevelActionPerformed

    private void txtGuardianOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianOccupationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSaveEnrollment;
    private javax.swing.JCheckBox chkDiagnosticPassed;
    private javax.swing.JCheckBox chkGoodMoralSubmitted;
    private javax.swing.JCheckBox chkHasAllergies;
    private javax.swing.JCheckBox chkPsaSubmitted;
    private javax.swing.JCheckBox chkSf10Submitted;
    private javax.swing.JComboBox<String> cmbEnrollmentStatus;
    private javax.swing.JComboBox<String> cmbGradeLevel;
    private javax.swing.JComboBox<String> cmbRelationship;
    private com.toedter.calendar.JDateChooser dateBirthdate;
    private com.toedter.calendar.JDateChooser dateDiagnosticSchedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextArea txtGuardianAddress;
    private javax.swing.JTextField txtGuardianContactNumber;
    private javax.swing.JTextField txtGuardianFirstName;
    private javax.swing.JTextField txtGuardianLastName;
    private javax.swing.JTextField txtGuardianOccupation;
    private javax.swing.JTextArea txtMedicalDetails;
    private javax.swing.JTextField txtPreviousSchool;
    private javax.swing.JTextArea txtStudentAddress;
    private javax.swing.JTextField txtStudentFirstName;
    private javax.swing.JTextField txtStudentLastName;
    private javax.swing.JTextField txtStudentMiddleName;
    // End of variables declaration//GEN-END:variables
}
