/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels.enrollment;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Pololoers
 */
public class ReEnrollmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReEnrollmentPanel
     */
    public ReEnrollmentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblCurrentGradeLevel = new javax.swing.JLabel();
        cmbNewGradeLevel = new javax.swing.JComboBox<>();
        dateDiagnosticSchedule = new com.toedter.calendar.JDateChooser();
        chkDiagnosticPassed = new javax.swing.JCheckBox();
        chkPsaSubmitted = new javax.swing.JCheckBox();
        chkSf10Submitted = new javax.swing.JCheckBox();
        chkGoodMoralSubmitted = new javax.swing.JCheckBox();
        cmbEnrollmentStatus = new javax.swing.JComboBox<>();
        btnSaveEnrollment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCheckBalance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitle.setText("Re Enroll Student");

        lblStudentName.setText("Student Name");

        lblCurrentGradeLevel.setText("Current Grade Level");

        cmbNewGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nursery", "Junior Kindergarten", "Senior Kindergarten", "1", "2", "3", "4", "5", "6" }));

        chkDiagnosticPassed.setText("Passed Diagnostic");

        chkPsaSubmitted.setText("PSA Submitted");

        chkSf10Submitted.setText("SF10 Submitted");

        chkGoodMoralSubmitted.setText("Good Moral Submitted");

        cmbEnrollmentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Enrolled", "Rejected" }));

        btnSaveEnrollment.setText("Save Enrollment");

        btnBack.setText("Back");

        btnCheckBalance.setText("Check Balance");
        btnCheckBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBalanceActionPerformed(evt);
            }
        });

        jLabel1.setText("Student Name:");

        jLabel2.setText("Enrollment Status");

        jLabel3.setText("Diagnostic Test Schedule");

        jLabel4.setText("Old Grade Level:");

        jLabel5.setText("New Grade Level:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveEnrollment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBack)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDiagnosticPassed)
                            .addComponent(chkPsaSubmitted)
                            .addComponent(chkSf10Submitted)
                            .addComponent(chkGoodMoralSubmitted)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEnrollmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateDiagnosticSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCurrentGradeLevel)
                                    .addComponent(lblStudentName)
                                    .addComponent(cmbNewGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentGradeLevel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNewGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateDiagnosticSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDiagnosticPassed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPsaSubmitted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSf10Submitted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkGoodMoralSubmitted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEnrollmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnSaveEnrollment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckBalance)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckBalanceActionPerformed

    public JLabel getLblStudentName() {
        return lblStudentName;
    }

    public JLabel getLblCurrentGradeLevel() {
        return lblCurrentGradeLevel;
    }

    public JComboBox<String> getCmbNewGradeLevel() {
        return cmbNewGradeLevel;
    }

    public JComboBox<String> getCmbEnrollmentStatus() {
        return cmbEnrollmentStatus;
    }

    public JDateChooser getDateDiagnosticSchedule() {
        return dateDiagnosticSchedule;
    }

    public JCheckBox getChkDiagnosticPassed() {
        return chkDiagnosticPassed;
    }

    public JCheckBox getChkPsaSubmitted() {
        return chkPsaSubmitted;
    }

    public JCheckBox getChkSf10Submitted() {
        return chkSf10Submitted;
    }

    public JCheckBox getChkGoodMoralSubmitted() {
        return chkGoodMoralSubmitted;
    }

    public JButton getBtnSaveEnrollment() {
        return btnSaveEnrollment;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnCheckBalance() {
        return btnCheckBalance;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckBalance;
    private javax.swing.JButton btnSaveEnrollment;
    private javax.swing.JCheckBox chkDiagnosticPassed;
    private javax.swing.JCheckBox chkGoodMoralSubmitted;
    private javax.swing.JCheckBox chkPsaSubmitted;
    private javax.swing.JCheckBox chkSf10Submitted;
    private javax.swing.JComboBox<String> cmbEnrollmentStatus;
    private javax.swing.JComboBox<String> cmbNewGradeLevel;
    private com.toedter.calendar.JDateChooser dateDiagnosticSchedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCurrentGradeLevel;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
