/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.maintenance;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Pololoers
 */
public class MaintenanceView extends javax.swing.JPanel {

    /**
     * Creates new form MaintenanceView
     */
    public MaintenanceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCreateBackup = new javax.swing.JButton();
        btnRestoreBackup = new javax.swing.JButton();
        btnArchiveRecords = new javax.swing.JButton();
        lblLastBackup = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 255));

        btnCreateBackup.setText("Create Backup");
        btnCreateBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBackupActionPerformed(evt);
            }
        });

        btnRestoreBackup.setText("Restore Backup");

        btnArchiveRecords.setText("Archive Backup");

        lblLastBackup.setText("Last Backup");

        lblStatus.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(456, 456, 456)
                                .addComponent(lblStatus)
                                .addGap(35, 35, 35)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRestoreBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnArchiveRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastBackup))))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(89, 89, 89)
                .addComponent(btnCreateBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRestoreBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnArchiveRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLastBackup)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateBackupActionPerformed

    // ============ GETTERS ============
    public JButton getBtnCreateBackup() {
        return btnCreateBackup;
    }

    public JButton getBtnRestoreBackup() {
        return btnRestoreBackup;
    }

    public JButton getBtnArchiveRecords() {
        return btnArchiveRecords;
    }

    public JLabel getLblLastBackup() {
        return lblLastBackup;
    }

    public JLabel getLblStatus() {
        return lblStatus;
    }

    public JProgressBar getProgressBar() {
        return progressBar;
    }

// ============ HELPERS ============
    /**
     * Updates status label
     */
    public void setStatus(String message) {
        lblStatus.setText(message);
    }

    /**
     * Updates last backup label
     */
    public void setLastBackup(String date) {
        lblLastBackup.setText("Last Backup: " + date);
    }

    /**
     * Sets progress bar value (0-100)
     */
    public void setProgress(int value) {
        progressBar.setValue(value);
    }

    /**
     * Enables/disables all buttons
     */
    public void setButtonsEnabled(boolean enabled) {
        btnCreateBackup.setEnabled(enabled);
        btnRestoreBackup.setEnabled(enabled);
        btnArchiveRecords.setEnabled(enabled);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchiveRecords;
    private javax.swing.JButton btnCreateBackup;
    private javax.swing.JButton btnRestoreBackup;
    private javax.swing.JLabel lblLastBackup;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
